### ISSUE TITLE
backdoored

### ISSUE THREAD

**Issue by waf22a** [De-eloper/XWorm#1]
asyncrat يا برنس البرنامج ملغم ب

**Comment by De-eloper** [comment]
Hey, can you show me where the backdoor is or where it connects to. I will delete the repository if I can find a backdoor in this rat. Thanks for telling me of this

**Comment by unkwnting** [comment]
Yes, you are absolutely right, the program is combined with the XwormClient load
We advise deleting this repository

**Comment by De-eloper** [comment]
> Yes, you are absolutely right, the program is combined with the XwormClient load We advise deleting this repository

Check the image, nothing is combined on my side. Could you make a video or show when it happens? I checked.
![xworme](https://user-images.githubusercontent.com/113988354/200366917-31f1fa58-3b40-4ded-834a-ab7fa07dd24d.PNG)

**Comment by waf22a** [comment]
AV flags when opening a remote desktop

**Comment by De-eloper** [comment]
I will leave a warning on main repository, it will take a while but the binaries (plugin and xworm) are unobfuscated. I will try look through them all in dnspy and if I find malicous code I will try to clean it off. Thanks.

**Comment by unkwnting** [comment]
sorry for the inconvenience, you are right, this repository does not contain any binders, both internal and external
If you carefully study the full code, you can understand that it does not hide anything malicious behind it.
I have all the possibilities including knowledge of the language based on the written project to find out if there is a virus in the project, but I can’t tell you for sure if your version has xworm, by the way you have a good chance of writing something like this if you disassemble the code njrat and xworm code, it's very simple, even a beginner will figure out the simplest clipboard replacement via cloud storage

![image](https://user-images.githubusercontent.com/112949116/200653649-4129f420-e00c-4da6-aaff-9b2c9d0814f3.png)

**Comment by De-eloper** [comment]
> sorry for the inconvenience, you are right, this repository does not contain any binders, both internal and external If you carefully study the full code, you can understand that it does not hide anything malicious behind it. I have all the possibilities including knowledge of the language based on the written project to find out if there is a virus in the project, but I can’t tell you for sure if your version has xworm, by the way you have a good chance of writing something like this if you disassemble the code njrat and xworm code, it's very simple, even a beginner will figure out the simplest clipboard replacement via cloud storage
> 
> ![image](https://user-images.githubusercontent.com/112949116/200653649-4129f420-e00c-4da6-aaff-9b2c9d0814f3.png)

It is no problem, I will still leave a warning that the program may be infected until I verify through decompilation of all plugins. I didn't have the source code to the remote access trojan but I have upload here so people aren't infected with binded version. I had written before a version of njrat that I opened source for and the xworm project is based on asyncrats old vb.net version (https://github.com/TheWover/AsyncRAT-VB.NET). I might try to write something similar to xworm in future and release the source for all.

**Comment by unkwnting** [comment]
Yes, I understand, but your project njrat horron practically does not work
More precisely, it has gaps in terms of creating files, and this affects a lot
![image](https://user-images.githubusercontent.com/112949116/200660509-4f9c3e20-7608-4e95-aa84-896458ee546c.png)

**Comment by unkwnting** [comment]
Yes, I understand, but your project njrat horron practically does not work
More specifically, it has gaps in terms of creating files, and this affects a lot

![image](https://user-images.githubusercontent.com/112949116/200660719-25f59781-8fba-43dc-b958-a7e37e247211.png)

**Comment by De-eloper** [comment]
I will close issue for now while I research if xworm plugins are infected or not. If there are any other issue or info, please open a new one. Thanks to all.
